language: node_js
node_js:
- node
cache: yarn
script: make ci
before_deploy: yarn version --no-git-tag-version --new-version "$TRAVIS_TAG"
deploy:
  provider: npm
  skip_cleanup: true
  email: e@lqnt.co
  api_key:
    secure: HMNDvGPnyylSEZregw43sX3dfAPHMbZ5+aPDBps5ufS1wgmwGuidcbhQ84JzAMb3LqkAMzsJ38vRYfB8qsT2u06LOSqR2FmRmyAvzr2xmItL2/XBi0NjxXKFOV34PdEUNSXM+B68+3hezQs0OecrGPXfK3mS7bsObS+SWjBJy/D2fQ9wt2upscLrWYma9deWNdMu0MtteRyDsFSo/eHZdk8JbM0jwiea3qGyiRqqAh9kQSKQUNnQjZ+RijxvZyCkX5vU5/qiCjdL4FtV5NXPAeVhLsmkIp81SI0GW85aqfHFfVf3U4aUK43N2bqIpahzf3tMzb5zv3Ad9GidvhWMezP/I8WU/Ic/ZzaMVxzGM/Qr+IDE8qyyk2oKu8iU6BFYAJkcd7MsO/kvNSquDI1/OOxppvrkiG/DePIMO78K+C+BhouCmf/lKcTY0T9h5TiJPBpTJ1Y284ymW9asl8fqM7CEI26pB60TytaQVuamYL1yM0ttnodCv4zhVXOGVdVeRYfDBvcD5/ukx/nXtqeABA3G7YIqRBD6LNBrvIhlJDImRsbwt7xOGwr7DMaxbUQAU3szz3N42gRHzX4nubUEKxNZNR7gPda+wyFHchTj7BnHBi/5tdgWoosmMXmEubmISyLjM6kK9hXiu0tQOWslGhiKal1sFg8H/Ra5fab5to0=
  on:
    tags: true
