language: node_js
node_js:
- node
cache: yarn
script: make ci
before_deploy: yarn version --no-git-tag-version --new-version "$TRAVIS_TAG"
deploy:
  provider: npm
  skip_cleanup: true
  email: e@lqnt.co
  api_key:
    secure: IIQ1RTqfw5OV/HtxST81JyX7cp2wfSKut4+wvmciBi3qlfpV+kolqTuuFNONdrF/WXuLj72WW4BYeOZidKIHl2Bp13b1JBINghAiXEoA1So5M0azGDKr3pFR92Qo6L55QnUOo/ec1i7RO29WJHAw2Tdn7DKArGfsMPaWPpy1bXl0p5NMSQbpIhelIFDdRUv9IUym0KWWaUr7yqbV5jv7KxK3odK9vGpJX+/fn8r87hA2d99WnuB+rFC7ibKeZZMniWWmyyZe8zNLosv0SN/XJR5Z6MuooPHx8wsm63AQG9sIPW63QToOub7nEAS2b/1Y4NfbXu7yIKmmP8FGtHhVeqs9L1Ui+RekQrOGuZtNb917KLGkrYzyvBlHveLFO7nWimphkVq5HZwyNqoZ2EXd7KRJNiqoCweDf9efTyieTEl5qBjWM8MQ+2KQOhAyf2c1AaX7Q8yBoDdrQSU3C9crRJln9lMauG3JX8i8XkmD0IklqQ26GJc7pkbw33DzY66BWqPfrNUGhelK0Gq1l9MZ/gda8zqEn//K4WEqk2EsDxawae//acdV8yX6n2bU2wDJ9Ex5GgtDI+FkVnGdNKSZgg+LI/Tr+keNAykAlzUvuKk9uQmEEYFEIEaVTokG9SKL897d+MXr1l0AEnQ2n2+sEhiFnzzx+1FPFzR99CXQWKg=
  on:
    tags: true
