name: Package
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '*'
        registry-url: 'https://registry.npmjs.org'
    - name: Check Node.js version
      run: node -v
    - name: Install dependencies
      run: make node_modules
    - name: Make
      run: make ci
    - name: Set package version
      run: make set-package-version
    - name: Publish package
      if: success()
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
